### ISSUE TITLE
Query About DNS Field Support

### ISSUE THREAD

**Issue by Zhichao-Zhang** [tumi8/zmap#10]
Hi!
Does the ipv6 dns module supports the extraction of specific DNS fields during a scan using -f parameters? such as *dns-id, dns-qr, dns-opcode, dns-rcode, dns-questions, dns-answers, dns-authorities, and dns-additional.*  I didnt see the support when using 'zmap --list-output-fields' command.

Thank you for your time and the effort put into developing zmapv6. Looking forward to your response.

**Comment by ogasser** [comment]
This is currently not implemented in ZMapv6's DNS module. A pull request to add this functionality is of course welcome!
